### ISSUE TITLE
fix weird `require`

### ISSUE THREAD

**Issue by VinSpee** [maoberlehner/retry-until-online#13]
```
 warning  in ./~/retry-until-online/dist/index.min.js

Critical dependencies:
1:94-101 require function is used in a way in which dependencies cannot be statically extracted
```

as far as I can tell, this is due to some fight between webpack and typescript (https://stackoverflow.com/questions/38392697/webpack-umd-critical-dependency-cannot-be-statically-extracted)

**Comment by VinSpee** [comment]
also let me add: I LOVE this module! Thank you!

**Comment by maoberlehner** [comment]
Hey @VinSpee!

Thanks for the nice feedback and for opening this issue.
For this reason (and some others) I'm planning to move back from TypeScript to regular ol JavaScript in the near future which will solve this issue.

In the future I'll generate both, an `umd` build (for browsers) and an `es` build (for bundlers like webpack). Currently I can't just create an additional `es` build with TypeScript, because I'm using TypeScript specific `export = ...` syntax (TypeScript is weird sometimes).

For now you can checkout the following technique as a workaround: https://stackoverflow.com/questions/43173706/importing-umd-built-module-using-webpack-leads-to-critical-dependency-errors/48823734#48823734

I'll update this issue as soon as the new build is ready.

Thx!

**Comment by VinSpee** [comment]
thank you! Works great.
